// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloworld.proto

package io.grpc.examples.helloworld.proto;

public interface HelloRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:helloworld.HelloRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string hello = 1;</code>
   * @return The hello.
   */
  String getHello();
  /**
   * <code>string hello = 1;</code>
   * @return The bytes for hello.
   */
  com.google.protobuf.ByteString
      getHelloBytes();

  /**
   * <code>string world = 2;</code>
   * @return The world.
   */
  String getWorld();
  /**
   * <code>string world = 2;</code>
   * @return The bytes for world.
   */
  com.google.protobuf.ByteString
      getWorldBytes();
}
